class Solution {
    public List<List<Integer>> threeSum(int[] nums) {
          Arrays.sort(nums);
                  List<List<Integer>> result = new ArrayList<>();
                          int n = nums.length;

                                  // Iterate through the array to fix the first element of the triplet
                                          for (int i = 0; i < n - 2; i++) {
                                                      // Skip duplicate values for the first element
                                                                  if (i > 0 && nums[i] == nums[i - 1]) {
                                                                                  continue;
                                                                                              }

                                                                                                          int left = i + 1;
                                                                                                                      int right = n - 1;
                                                                                                                                  int target = -nums[i]; // We want nums[left] + nums[right] to equal -nums[i]

                                                                                                                                              // Use the two-pointer technique to find the remaining two elements
                                                                                                                                                          while (left < right) {
                                                                                                                                                                          int currentSum = nums[left] + nums[right];

                                                                                                                                                                                          if (currentSum == target) {
                                                                                                                                                                                                              // Found a valid triplet
                                                                                                                                                                                                                                  result.add(Arrays.asList(nums[i], nums[left], nums[right]));

                                                                                                                                                                                                                                                      // Skip duplicate values for the second and third elements
                                                                                                                                                                                                                                                                          while (left < right && nums[left] == nums[left + 1]) {
                                                                                                                                                                                                                                                                                                  left++;
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                          while (left < right && nums[right] == nums[right - 1]) {
                                                                                                                                                                                                                                                                                                                                                                  right--;
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                          // Move both pointers inward to find the next unique pair
                                                                                                                                                                                                                                                                                                                                                                                                                              left++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  right--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else if (currentSum < target) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Sum is too small, move the left pointer to increase the sum
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          left++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Sum is too large, move the right pointer to decrease the sum
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  right--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return result; 
    }
}